FROM python:3.10-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY python/ ./

RUN mkdir -p uploads

# expose port
EXPOSE 8000

# finally
CMD ["python", "api.py"]
