services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: edgeup-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: edgeup
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - edgeup-network

  # Python FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: edgeup-backend
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/edgeup?authSource=admin
    env_file:
      - python/.env
    volumes:
      - ./uploads:/app/uploads
      - ./python:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - edgeup-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # React Frontend with Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: edgeup-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - edgeup-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  edgeup-network:
    driver: bridge

volumes:
  mongodb_data:
  uploads:
