services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: edgeup-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - python/.env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - edgeup-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: edgeup-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - edgeup-network
    restart: unless-stopped

networks:
  edgeup-network:
    driver: bridge

volumes:
  uploads:
